version: '3.4'

services:
  db:
    image: postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: "postgres"

  web:
    depends_on:
      - 'db'
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: "db"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_PORT: "5432"